"""
旅行周报自动生成服务
满足作业8加分项：自动生成周报/日报
"""
import os
from datetime import datetime, timedelta
from services.data_storage import load_weather_history, load_alert_history
from services.anomaly_detection import get_alert_summary
from services.linkage_service import get_travel_recommendation_summary

# 使用项目根目录的绝对路径
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def generate_weekly_report():
    """
    生成周报
    """
    today = datetime.now()
    week_start = today - timedelta(days=7)
    
    # 加载数据
    weather_history = load_weather_history()
    alert_history = load_alert_history()
    
    # 过滤本周数据
    week_alerts = [
        alert for alert in alert_history
        if datetime.fromisoformat(alert["timestamp"]) >= week_start
    ]
    
    # 统计各城市天气情况
    city_stats = {}
    for city, records in weather_history.items():
        city_week_records = [
            r for r in records
            if datetime.fromisoformat(r["timestamp"]) >= week_start
        ]
        
        if city_week_records:
            temps = [r["data"].get("temperature", 0) for r in city_week_records]
            humidities = [r["data"].get("humidity", 0) for r in city_week_records]
            
            city_stats[city] = {
                "record_count": len(city_week_records),
                "avg_temp": round(sum(temps) / len(temps), 1) if temps else 0,
                "max_temp": max(temps) if temps else 0,
                "min_temp": min(temps) if temps else 0,
                "avg_humidity": round(sum(humidities) / len(humidities), 1) if humidities else 0,
                "conditions": [r["data"].get("condition", "未知") for r in city_week_records[-3:]]
            }
    
    # 告警统计
    alert_stats = {}
    for alert in week_alerts:
        alert_type = alert.get("alert_type", "未知")
        alert_stats[alert_type] = alert_stats.get(alert_type, 0) + 1
    
    # 生成报告
    report = f"""# 🌤️ 旅行天气周报

**报告周期**：{(week_start).strftime('%Y年%m月%d日')} - {today.strftime('%Y年%m月%d日')}  
**生成时间**：{today.strftime('%Y年%m月%d日 %H:%M')}

---

## 📊 数据概览

| 指标 | 数值 |
|------|------|
| 监测城市数 | {len(city_stats)} |
| 天气记录数 | {sum(s['record_count'] for s in city_stats.values())} |
| 告警总数 | {len(week_alerts)} |
| 告警城市数 | {len(set(a['city'] for a in week_alerts))} |

---

## 🌡️ 城市天气统计

"""

    for city, stats in city_stats.items():
        conditions_text = "、".join(set(stats["conditions"]))
        report += f"""### {city}

- 平均气温：{stats['avg_temp']}°C
- 最高/最低：{stats['max_temp']}°C / {stats['min_temp']}°C
- 平均湿度：{stats['avg_humidity']}%
- 主要天气：{conditions_text}
- 数据记录：{stats['record_count']}条

"""

    # 告警分析
    report += """---

## ⚠️ 告警分析

"""

    if week_alerts:
        report += "| 告警类型 | 次数 | 涉及城市 |\n"
        report += "|----------|------|----------|\n"
        
        alert_city_count = {}
        for alert in week_alerts:
            alert_type = alert.get("alert_type", "未知")
            city = alert.get("city", "未知")
            if alert_type not in alert_city_count:
                alert_city_count[alert_type] = {"count": 0, "cities": set()}
            alert_city_count[alert_type]["count"] += 1
            alert_city_count[alert_type]["cities"].add(city)
        
        for alert_type, data in alert_city_count.items():
            cities = "、".join(data["cities"])
            report += f"| {alert_type} | {data['count']} | {cities} |\n"
        
        # 详细告警列表
        report += "\n### 告警详情\n\n"
        
        for alert in week_alerts[-5:]:  # 最近5条
            alert_time = datetime.fromisoformat(alert["timestamp"]).strftime("%m月%d日 %H:%M")
            report += f"""**{alert['city']}** - {alert_time}
> {alert['message'][:100]}...

"""
    else:
        report += "本周无告警记录，天气状况良好！✅\n\n"

    # 旅行建议总结
    report += """---

## 💡 旅行建议总结

"""

    # 根据天气情况给出建议
    if any(stats['avg_temp'] >= 32 for stats in city_stats.values()):
        report += "⚠️ **高温提醒**：部分城市气温较高，建议避开中午时段户外活动\n\n"
    
    if any(stats['avg_temp'] <= 5 for stats in city_stats.values()):
        report += "❄️ **低温提醒**：部分城市气温较低，请做好保暖措施\n\n"
    
    if any('雨' in ' '.join(stats['conditions']) for stats in city_stats.values()):
        report += "🌧️ **降水提醒**：部分城市有降雨，出行请携带雨具\n\n"
    
    if not week_alerts:
        report += "🌈 整体来看，本周天气条件较为稳定，适合各类旅行活动。\n\n"

    # 下周展望
    report += f"""---

## 🔮 下周展望

基于本周数据分析，预计下周天气趋势：
- 建议关注城市：{', '.join(list(city_stats.keys())[:3]) if city_stats else '暂无数据'}
- 重点关注：气温变化和空气质量

---

**报告说明**：本报告基于实时天气数据自动生成，数据仅供参考。如需更详细的信息，请访问天气数据看板。

*Generated by Travel Assistant*
"""

    return report


def generate_daily_brief():
    """
    生成日报摘要（简化版）
    """
    today = datetime.now()
    
    # 加载数据
    weather_history = load_weather_history()
    alerts = load_alert_history()
    
    # 获取今日数据
    today_str = today.strftime("%Y-%m-%d")
    today_alerts = [
        a for a in alerts
        if a["timestamp"].startswith(today_str) and not a.get("resolved", False)
    ]
    
    # 各城市今日天气
    today_weather = {}
    for city, records in weather_history.items():
        today_records = [
            r for r in records
            if r["timestamp"].startswith(today_str)
        ]
        if today_records:
            today_weather[city] = today_records[-1]["data"]
    
    # 生成简短报告
    brief = f"""📅 {today.strftime('%Y年%m月%d日')} 天气日报

{'='*40}

🌤️ 今日天气概览：
• 监测城市：{len(today_weather)}个
• 活跃告警：{len(today_alerts)}条

"""

    if today_weather:
        brief += "各城市天气：\n"
        for city, data in list(today_weather.items())[:5]:
            brief += f"• {city}：{data.get('condition', '未知')} {data.get('temperature', '?')}°C\n"
    
    if today_alerts:
        brief += "\n⚠️ 今日告警：\n"
        for alert in today_alerts[:3]:
            brief += f"• {alert['city']}：{alert['alert_type']}\n"
    
    brief += "\n" + "="*40 + "\n"
    brief += "💡 建议："
    
    if not today_alerts and today_weather:
        brief += "今日天气良好，适合出行！"
    elif today_alerts:
        brief += "有告警信息，请注意防范。"
    else:
        brief += "暂无数据"
    
    return brief


def save_report_to_file(report, filename=None):
    """保存报告到文件（保存到项目 reports/ 目录）"""
    reports_dir = os.path.join(PROJECT_ROOT, "reports")
    if not os.path.exists(reports_dir):
        os.makedirs(reports_dir)

    if filename is None:
        filename = f"travel_report_{datetime.now().strftime('%Y%m%d_%H%M')}.md"

    filepath = os.path.join(reports_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    return filepath


# API端点需要在app.py中定义